SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE
JOIN (SELECT *
      FROM USED_GOODS_BOARD
      ORDER BY VIEWS DESC
      LIMIT 1) AS B
USING (BOARD_ID)
ORDER BY FILE_ID DESC;

