-- 코드를 입력하세요
SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM PATIENT p
INNER JOIN APPOINTMENT a
ON p.PT_NO = a.PT_NO
INNER JOIN DOCTOR d
ON d.DR_ID = a.MDDR_ID
WHERE a.APNT_YMD LIKE '2022-04-13%'
AND a.APNT_CNCL_YN = 'N'
ORDER BY a.APNT_YMD