-- 코드를 입력하세요
SELECT B.HI AS HISTORY_ID,
IF(A.DISCOUNT_RATE IS NULL, (B.D) * (B.DF), round((100-A.DISCOUNT_RATE)/100*(B.DF)) * B.D)AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN A
RIGHT JOIN
(SELECT H.history_id AS HI, C.car_type AS CT, DATEDIFF(H.end_date, H.start_date)+1 AS D, C.daily_fee AS DF,
CASE
 WHEN DATEDIFF(H.end_date,H.start_date)+1 >=90 THEN '90일 이상'
 WHEN DATEDIFF(H.end_date,H.start_date)+1 >=30 THEN '30일 이상'
 WHEN DATEDIFF(H.end_date,H.start_date)+1 >=7 THEN '7일 이상'
END AS DT
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
 LEFT JOIN CAR_RENTAL_COMPANY_CAR C
 ON H.CAR_ID = C.CAR_ID
 WHERE CAR_TYPE='트럭'
) B
ON B.CT=A.CAR_TYPE AND A.DURATION_TYPE=B.DT
ORDER BY FEE DESC, HISTORY_ID DESC;